[terminal]
[terminal.shell]
program = "wsl.exe"

[font]
normal = { family = "Iosevka Nerd Font" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
size = 12

[window]
decorations = "None"
blur = true
opacity = 8.5
[window.padding]
x = 8 
y = 8

[keyboard]
[[keyboard.bindings]]
key = "Space"
mods = "alt"
action = "ToggleFullscreen"

