[font]
normal = { family = "Iosevka Nerd Font" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
size = 12
[window]
opacity = 0.7
blur = true
